esphome:
  name: $name
  project:
    name: Cree Lighting.CMACC-CMSC-UNV-WH 5-Button Scene Controller
    version: "1"
bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "a36cc7ff477b90ab769620ffd5931366"
    
web_server:
  port: 80
  include_internal: true

captive_portal:

mdns:

wifi:
  ssid: $wifi_ssid
  password: $wifi_password

  ap:
    ssid: "$friendly_name"
    password: "JbP6CAWsWCnr"

event:
  - platform: template
    id: button_press
    name: ${friendly_name} Button Press
    event_types:
      - "button_1_pressed"
      - "button_2_pressed"
      - "button_3_pressed"
      - "button_4_pressed"
      - "button_5_pressed"

binary_sensor:
  - platform: status
    name: ${friendly_name} Status

  - platform: gpio
    name: "Button 1"
    pin:
      number: 20
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - event.trigger: 
            id: button_press
            event_type: button_1_pressed

  - platform: gpio
    name: "Button 2"
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - event.trigger: 
            id: button_press
            event_type: button_2_pressed

  - platform: gpio
    name: "Button 3"
    pin:
      number: 28
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - event.trigger: 
            id: button_press
            event_type: button_3_pressed

  - platform: gpio
    name: "Button 4"
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - event.trigger: 
            id: button_press
            event_type: button_4_pressed

  - platform: gpio
    name: "Button 5"
    pin:
      number: 15
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - event.trigger: 
            id: button_press
            event_type: button_5_pressed
button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      icon: mdi:ip-network

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime

  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal

light:
  - platform: status_led
    name: ${friendly_name} status
    id: led_status_light
    entity_category: diagnostic
    pin:
      number: P23
      inverted: true
